CONTROL_DIR = Control/
CONTROL_PATH = $(SRC_PATH)$(CONTROL_DIR)
CONTROL_OBJ_PATH = $(BUILD_RESULT_PATH)$(CONTROL_DIR)
CONTROL_INC = \
	-I$(WATCHDOG_PATH) \
	-I$(INTERRUPT_PATH) \
	-I$(GPIO_PATH)
# 	-I$(UART_PATH)
